{
 "title": "Nginx Public Access",
 "tags": [
  "nginx",
  "public"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service=\"nginx.service\"} |= \"nginx_public\" [$__range]))"
    }
   ]
  },
  {
   "title": "Error Requests (4xx/5xx)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service=\"nginx.service\"} |= \"nginx_public\" | pattern `<_> nginx_public: <ip> - <_> [<_>] \"<_> <_> <_>\" <status> <_> \"<_>\" \"<_>\" host=<_>` | status >= 400 [$__range]))"
    }
   ]
  },
  {
   "title": "Unique IPs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "expr": "sum by (ip) (count_over_time({service=\"nginx.service\"} |= \"nginx_public\" | pattern `<_> nginx_public: <ip> - <_> [<_>] \"<_> <_> <_>\" <_> <_> \"<_>\" \"<_>\" host=<_>` [$__range]))"
    }
   ]
  },
  {
   "title": "Requests by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({service=\"nginx.service\"} |= \"nginx_public\" | pattern `<_> nginx_public: <_> - <_> [<_>] \"<_> <_> <_>\" <status> <_> \"<_>\" \"<_>\" host=<_>` [$__auto]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests by Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (host) (count_over_time({service=\"nginx.service\"} |= \"nginx_public\" | pattern `<_> nginx_public: <_> - <_> [<_>] \"<_> <_> <_>\" <_> <_> \"<_>\" \"<_>\" host=<host>` [$__auto]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Requests by Client IP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum by (ip) (count_over_time({service=\"nginx.service\"} |= \"nginx_public\" | pattern `<_> nginx_public: <ip> - <_> [<_>] \"<_> <_> <_>\" <_> <_> \"<_>\" \"<_>\" host=<_>` [$__auto]))",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Top Requested Paths",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by (path) (count_over_time({service=\"nginx.service\"} |= \"nginx_public\" | pattern `<_> nginx_public: <_> - <_> [<_>] \"<_> <path> <_>\" <_> <_> \"<_>\" \"<_>\" host=<_>` [$__range]))"
    }
   ]
  },
  {
   "title": "Top User Agents",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum by (user_agent) (count_over_time({service=\"nginx.service\"} |= \"nginx_public\" | pattern `<_> nginx_public: <_> - <_> [<_>] \"<_> <_> <_>\" <_> <_> \"<_>\" \"<user_agent>\" host=<_>` [$__range]))"
    }
   ]
  },
  {
   "title": "Access Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{service=\"nginx.service\"} |= \"nginx_public\""
    }
   ]
  }
 ]
}